include:
  - board: nice_nano_v2
    shield: tempest_left
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: tempest_right
  - board: nice_nano_v2
    shield: settings_reset