# Uncomment the following line to enable the Tempest OLED Display
# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
# CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Use higher power BT for better connection/latency
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Device power management (PM) enables devices to save energy when they are not being used
CONFIG_PM_DEVICE=y

# Sleep/Idle
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Eager debounce for presses. Increase if you have issues with double-presses.
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15
